<?php

namespace AppBundle\Repository;

/**
 * CarpecajaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarpecajaRepository extends \Doctrine\ORM\EntityRepository
{
}
