<?php

namespace AppBundle\Repository;

/**
 * DepcajasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepcajasRepository extends \Doctrine\ORM\EntityRepository
{
}
