<?php

namespace AppBundle\Repository;

/**
 * HistarchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistarchRepository extends \Doctrine\ORM\EntityRepository
{
}
