<?php

namespace AppBundle\Repository;

/**
 * LadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LadosRepository extends \Doctrine\ORM\EntityRepository
{
}
